//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isc210_3_2018_2019_rpg_webapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scores
    {
        public int IdScore { get; set; }
        public string PlayerName { get; set; }
        public double Score { get; set; }
    }
}
